name: Java Check Style

on:
  push:
    branches:
      - master

jobs:

  java-check-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Google Java Format
        run: |
          java -jar /opt/google-java-format/google-java-format.jar --dry-run --set-exit-if-changed $(find . -name "*.java")