name: Java Check Style

on:
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run lint
        run: |
          javac -Xlint:all $(find . -name "*.java")