name: Java Check Style

on:
  push:
    branches:
      - master

jobs:

  java-check-style:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set Java version
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.2'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Run Checkstyle
        run: |
          mvn checkstyle:checkstyle